/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FieldError } from './fieldError';


export interface ApiError { 
    code?: string;
    message?: string;
    fieldErrors?: Array<FieldError>;
}

