/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApiError } from './apiError';


export interface ApiResponseVoid { 
    success?: boolean;
    data?: any | null;
    error?: ApiError;
    timestamp?: string;
}

