/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CategoryOption } from './categoryOption';
import { ApiError } from './apiError';


export interface ApiResponseListCategoryOption { 
    success?: boolean;
    data?: Array<CategoryOption>;
    error?: ApiError;
    timestamp?: string;
}

