/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PageResponseRiskAlertListItem } from './pageResponseRiskAlertListItem';
import { ApiError } from './apiError';


export interface ApiResponsePageResponseRiskAlertListItem { 
    success?: boolean;
    data?: PageResponseRiskAlertListItem;
    error?: ApiError;
    timestamp?: string;
}

