/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApiError } from './apiError';
import { SupplierOption } from './supplierOption';


export interface ApiResponseListSupplierOption { 
    success?: boolean;
    data?: Array<SupplierOption>;
    error?: ApiError;
    timestamp?: string;
}

