/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApiError } from './apiError';
import { TokenPair } from './tokenPair';


export interface ApiResponseTokenPair { 
    success?: boolean;
    data?: TokenPair;
    error?: ApiError;
    timestamp?: string;
}

