/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApiError } from './apiError';
import { AuthenticatedUser } from './authenticatedUser';


export interface ApiResponseAuthenticatedUser { 
    success?: boolean;
    data?: AuthenticatedUser;
    error?: ApiError;
    timestamp?: string;
}

