/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TokenPair } from './tokenPair';
import { AuthenticatedUser } from './authenticatedUser';


export interface LoginResult { 
    tokens?: TokenPair;
    user?: AuthenticatedUser;
}

