/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RiskAlertListItem } from './riskAlertListItem';


export interface PageResponseRiskAlertListItem { 
    content?: Array<RiskAlertListItem>;
    page?: number;
    size?: number;
    totalElements?: number;
    totalPages?: number;
}

