/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProductListItem } from './productListItem';


export interface PageResponseProductListItem { 
    content?: Array<ProductListItem>;
    page?: number;
    size?: number;
    totalElements?: number;
    totalPages?: number;
}

