/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProductRequest { 
    name: string;
    categoryId: number;
    supplierId?: number;
    cost?: number;
    suggestedPrice?: number;
    moq?: number;
    season?: ProductRequest.SeasonEnum;
    trackType: ProductRequest.TrackTypeEnum;
    sourcingStatus?: ProductRequest.SourcingStatusEnum;
    logisticsCondition?: string;
    shelfLifeDays?: number;
    idealTempMin?: number;
    idealTempMax?: number;
    keywordIds?: Array<number>;
}
export namespace ProductRequest {
    export type SeasonEnum = 'ALL' | 'SPRING' | 'SUMMER' | 'AUTUMN' | 'WINTER' | 'FESTIVAL';
    export const SeasonEnum = {
        All: 'ALL' as SeasonEnum,
        Spring: 'SPRING' as SeasonEnum,
        Summer: 'SUMMER' as SeasonEnum,
        Autumn: 'AUTUMN' as SeasonEnum,
        Winter: 'WINTER' as SeasonEnum,
        Festival: 'FESTIVAL' as SeasonEnum
    };
    export type TrackTypeEnum = 'A' | 'B';
    export const TrackTypeEnum = {
        A: 'A' as TrackTypeEnum,
        B: 'B' as TrackTypeEnum
    };
    export type SourcingStatusEnum = 'PENDING' | 'SOURCING' | 'URGENT' | 'PROMOTED' | 'REJECTED';
    export const SourcingStatusEnum = {
        Pending: 'PENDING' as SourcingStatusEnum,
        Sourcing: 'SOURCING' as SourcingStatusEnum,
        Urgent: 'URGENT' as SourcingStatusEnum,
        Promoted: 'PROMOTED' as SourcingStatusEnum,
        Rejected: 'REJECTED' as SourcingStatusEnum
    };
}


