/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProductStatusChangeRequest { 
    status: ProductStatusChangeRequest.StatusEnum;
}
export namespace ProductStatusChangeRequest {
    export type StatusEnum = 'DRAFT' | 'EVALUATING' | 'WATCHING' | 'ADOPTED' | 'LISTED' | 'REJECTED';
    export const StatusEnum = {
        Draft: 'DRAFT' as StatusEnum,
        Evaluating: 'EVALUATING' as StatusEnum,
        Watching: 'WATCHING' as StatusEnum,
        Adopted: 'ADOPTED' as StatusEnum,
        Listed: 'LISTED' as StatusEnum,
        Rejected: 'REJECTED' as StatusEnum
    };
}


