/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RiskAlertListItem { 
    id?: number;
    productId?: number;
    productName?: string;
    categoryId?: number;
    categoryName?: string;
    riskType?: string;
    severity?: RiskAlertListItem.SeverityEnum;
    triggerValue?: string;
    status?: RiskAlertListItem.StatusEnum;
    ignoreReason?: string;
    detectedAt?: string;
    handledAt?: string;
    handledByName?: string;
}
export namespace RiskAlertListItem {
    export type SeverityEnum = 'HIGH' | 'MEDIUM' | 'LOW';
    export const SeverityEnum = {
        High: 'HIGH' as SeverityEnum,
        Medium: 'MEDIUM' as SeverityEnum,
        Low: 'LOW' as SeverityEnum
    };
    export type StatusEnum = 'OPEN' | 'ACKNOWLEDGED' | 'IGNORED';
    export const StatusEnum = {
        Open: 'OPEN' as StatusEnum,
        Acknowledged: 'ACKNOWLEDGED' as StatusEnum,
        Ignored: 'IGNORED' as StatusEnum
    };
}


