/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SourceDetail { 
    sourceName?: string;
    percentile?: number;
    actualWeight?: number;
    status?: string;
    slope7d?: number;
    slope30d?: number;
}

