/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SourceDetail } from './sourceDetail';


export interface TrendDetailResponse { 
    keyword?: string;
    heatToday?: number;
    slope7d?: number;
    slope30d?: number;
    aiSignal?: string;
    sourceDetails?: Array<SourceDetail>;
}

