/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TrendSignalProjection { 
    aiSignal?: string;
    keywordId?: number;
    keyword?: string;
    slope30d?: number;
    heatToday?: number;
    slope7d?: number;
}

