/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SceneWeightSet } from './sceneWeightSet';


export interface WeightVersionUpsertRequest { 
    name: string;
    changeNote?: string;
    effectiveFrom?: string;
    scenes: Array<SceneWeightSet>;
}

