-- ===================================================================
-- DRAFT - Shared AI execution attempts, retry scheduling and quota audit
--
-- Supports specification §6.7.3-§6.7.4 for every Agent. This file
-- intentionally lives outside db/migration and is not executed by Flyway.
-- Move it into db/migration only with the matching orchestration changes.
-- ===================================================================

ALTER TABLE ai_task_item
    ADD COLUMN attempt_count INT NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
    ADD COLUMN next_retry_at TIMESTAMPTZ,
    ADD COLUMN last_attempt_at TIMESTAMPTZ;

CREATE TABLE ai_attempt (
    id                BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_item_id      BIGINT       NOT NULL REFERENCES ai_task_item (id) ON DELETE CASCADE,
    attempt_no        INT          NOT NULL CHECK (attempt_no > 0),
    attempt_kind      VARCHAR(16)  NOT NULL
                      CHECK (attempt_kind IN ('PRIMARY', 'RETRY', 'FALLBACK')),
    budget_pool       VARCHAR(16)  NOT NULL
                      CHECK (budget_pool IN ('A_TRACK', 'B_TRACK', 'RESERVE')),
    model_alias       VARCHAR(32)  NOT NULL
                      CHECK (model_alias IN ('MODEL_CLASSIFY', 'MODEL_LONG_TEXT',
                                             'MODEL_SHORT_GEN', 'MODEL_NUMERIC',
                                             'MODEL_REASONING')),
    model_id          VARCHAR(120) NOT NULL,
    outcome           VARCHAR(24)  NOT NULL
                      CHECK (outcome IN ('SUCCESS', 'RATE_LIMITED', 'SCHEMA_INVALID',
                                         'TIMEOUT', 'HTTP_ERROR', 'NETWORK_ERROR',
                                         'CANCELLED')),
    http_status       INT          CHECK (http_status IS NULL OR http_status BETWEEN 100 AND 599),
    prompt_tokens     INT          CHECK (prompt_tokens IS NULL OR prompt_tokens >= 0),
    completion_tokens INT          CHECK (completion_tokens IS NULL OR completion_tokens >= 0),
    cost_usd          DECIMAL(10, 5) NOT NULL DEFAULT 0 CHECK (cost_usd >= 0),
    duration_ms       INT          CHECK (duration_ms IS NULL OR duration_ms >= 0),
    error_message     VARCHAR(500),
    raw_response      TEXT,
    started_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    completed_at      TIMESTAMPTZ,

    CONSTRAINT uk_ai_attempt_number UNIQUE (task_item_id, attempt_no),
    CONSTRAINT ck_ai_attempt_time CHECK (
        completed_at IS NULL OR completed_at >= started_at
    )
);

COMMENT ON TABLE ai_attempt IS
    '每次 OpenRouter 呼叫一列，包含主模型、重試與備援；供每日配額、失敗率及模型可用性統計';
COMMENT ON COLUMN ai_attempt.budget_pool IS
    'A_TRACK=批次評分 70%、B_TRACK=尋源 20%、RESERVE=重試與臨時任務 10%';
COMMENT ON COLUMN ai_attempt.raw_response IS
    '保留該次模型原始回應，讓 Schema 驗證失敗不會被下一次重試覆蓋';

CREATE INDEX idx_ai_task_item_retry
    ON ai_task_item (status, next_retry_at)
    WHERE status = 'FAILED' AND next_retry_at IS NOT NULL;
CREATE INDEX idx_ai_attempt_quota
    ON ai_attempt (budget_pool, started_at);
CREATE INDEX idx_ai_attempt_model_outcome
    ON ai_attempt (model_alias, model_id, outcome, started_at DESC);

