-- ===================================================================
-- V1 baseline schema
-- 團購產業 AI 採購選品策略系統（SSDS）
-- 對應：開發規格書 v2.0 §7 資料庫設計
-- ===================================================================
--
-- 【資料庫方言說明】
-- 規格書 §3.2 原訂 MySQL 8.0，但本專案實際佈署於 Supabase PostgreSQL，
-- 因此下列 MySQL 專屬寫法一律轉譯，語意不變：
--
--   MySQL                      PostgreSQL
--   ------------------------   --------------------------------------
--   BIGINT PK AUTO_INCREMENT   BIGINT GENERATED BY DEFAULT AS IDENTITY
--   ENUM('A','B')              VARCHAR + CHECK (col IN ('A','B'))
--   DATETIME                   TIMESTAMPTZ（規格書 §3.2：DB 存 UTC）
--   JSON                       JSONB（可建 GIN 索引、比對不需重新 parse）
--   TINYINT                    SMALLINT（PG 無 1 byte 整數型別）
--   utf8mb4                    PostgreSQL 預設即為 UTF-8，不需宣告
--   CHAR(n)                    VARCHAR(n)
--
-- 註：grade 與 track_type 這種「只放一個字母」的欄位也給 VARCHAR(8) 而非
-- VARCHAR(1)。原因是 Hibernate 對 @Enumerated(STRING) 且 length=1 的屬性
-- 會期待 JDBC 的 CHAR 型別，與 varchar 對不起來而讓 ddl-auto=validate 失敗。
-- 值的正確性本來就由 CHECK 約束把關，欄位長度不是防線。
--
-- CHAR(n) 一律改 VARCHAR(n) 的兩個理由：
--   1. PostgreSQL 的 bpchar 會以空白補滿到 n，content_hash 這種等值比對
--      會因為尾端空白而出現「看起來一樣卻不相等」的錯誤，MySQL 沒有這個坑。
--   2. PostgreSQL 的 CHAR 沒有任何儲存或效能優勢（內部一樣是變長）。
--   另外 Hibernate 的 ddl-auto=validate 會把 bpchar 與 String 的 JDBC
--   型別碼視為不符而啟動失敗，改 VARCHAR 同時省掉這個摩擦。
--
-- ENUM 改用 CHECK 而非 PostgreSQL 原生 enum type 的理由：
-- 原生 enum 新增值要 ALTER TYPE、移除值幾乎不可能，而本系統的
-- factor_code、scene_type 等會隨校準迭代增修（FR-15）。
-- CHECK 約束改起來就是一次 migration，且 Hibernate 直接以
-- @Enumerated(EnumType.STRING) 對應，不需自訂 UserType。
--
-- 【時間欄位】
-- 一律 TIMESTAMPTZ 並以 UTC 儲存，應用層轉 Asia/Taipei 顯示（§3.2）。
-- 純日期（stat_date、festival_date 等）用 DATE，不帶時區。
-- ===================================================================


-- ===================================================================
-- 使用者與權限（§7.2 app_user / role / user_role）
-- ===================================================================

CREATE TABLE app_user (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email           VARCHAR(150) NOT NULL UNIQUE,
    password_hash   VARCHAR(100) NOT NULL,
    display_name    VARCHAR(50)  NOT NULL,
    status          VARCHAR(16)  NOT NULL DEFAULT 'ACTIVE'
                    CHECK (status IN ('ACTIVE', 'DISABLED')),
    failed_attempts INT          NOT NULL DEFAULT 0,
    locked_until    TIMESTAMPTZ,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now()
);
COMMENT ON TABLE  app_user IS '系統使用者。password_hash 為 BCrypt 雜湊，永不儲存明碼';
COMMENT ON COLUMN app_user.failed_attempts IS '連續登入失敗次數，達門檻後寫入 locked_until 做時間鎖定';
COMMENT ON COLUMN app_user.locked_until IS '鎖定至此時刻；NULL 表未鎖定';

CREATE TABLE role (
    id          BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(32) NOT NULL UNIQUE
                CHECK (code IN ('BUYER', 'BUYER_LEAD', 'DATA_ADMIN', 'SYS_ADMIN', 'VIEWER')),
    name        VARCHAR(50) NOT NULL,
    description VARCHAR(200)
);
COMMENT ON TABLE  role IS '角色主檔，標準 RBAC。權限矩陣見規格書 §2.1';
COMMENT ON COLUMN role.code IS '對應 §2 角色代碼。Spring Security 的 hasRole 會自動補 ROLE_ 前綴，故此處不含前綴';

CREATE TABLE user_role (
    user_id BIGINT NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
    role_id BIGINT NOT NULL REFERENCES role (id)     ON DELETE CASCADE,
    PRIMARY KEY (user_id, role_id)
);
COMMENT ON TABLE user_role IS '使用者與角色的多對多關聯。一人可有多角色，取聯集權限';


-- ===================================================================
-- 品項主檔相關（§7.2 category / supplier / product / product_image）
-- ===================================================================

CREATE TABLE category (
    id         BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id  BIGINT      REFERENCES category (id),
    name       VARCHAR(50) NOT NULL,
    sort_order INT         NOT NULL DEFAULT 0
);
COMMENT ON TABLE  category IS '品類。§5.3.1 的同品類百分位正規化以此為分組依據';
COMMENT ON COLUMN category.parent_id IS '自我參照，支援兩層類別。NULL 表頂層；不做無限層級';

CREATE TABLE supplier (
    id      BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR(100) NOT NULL,
    contact VARCHAR(50),
    phone   VARCHAR(30),
    note    VARCHAR(500)
);
COMMENT ON TABLE supplier IS '供應商。B 軌品項在成案前 supplier_id 為 NULL';

CREATE TABLE product (
    id                  BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                VARCHAR(100)  NOT NULL,
    category_id         BIGINT        NOT NULL REFERENCES category (id),
    supplier_id         BIGINT        REFERENCES supplier (id),
    cost                DECIMAL(10, 2),
    suggested_price     DECIMAL(10, 2),
    margin_rate         DECIMAL(5, 4),
    moq                 INT,
    season              VARCHAR(16)   NOT NULL DEFAULT 'ALL'
                        CHECK (season IN ('ALL', 'SPRING', 'SUMMER', 'AUTUMN', 'WINTER', 'FESTIVAL')),
    target_audience     VARCHAR(200),
    status              VARCHAR(16)   NOT NULL DEFAULT 'DRAFT'
                        CHECK (status IN ('DRAFT', 'EVALUATING', 'WATCHING', 'ADOPTED', 'LISTED', 'REJECTED')),
    reject_reason       VARCHAR(500),
    listed_at           DATE,

    -- ---- v2.0 新增欄位（§7.2 既有資料表變更）----
    track_type          VARCHAR(8)      NOT NULL DEFAULT 'A' CHECK (track_type IN ('A', 'B')),
    sourcing_status     VARCHAR(24)
                        CHECK (sourcing_status IN ('PENDING', 'SOURCING', 'URGENT', 'PROMOTED', 'REJECTED')),
    logistics_condition VARCHAR(100),
    shelf_life_days     INT,

    created_by          BIGINT        REFERENCES app_user (id),
    created_at          TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ   NOT NULL DEFAULT now(),

    -- 售價不得低於成本，否則毛利率為負，評分無意義
    CONSTRAINT ck_product_price CHECK (
        cost IS NULL OR suggested_price IS NULL OR suggested_price >= cost
    ),
    -- A 軌一定要有成本與售價才算得出毛利率；草稿與 B 軌允許留白
    CONSTRAINT ck_product_track_a_pricing CHECK (
        track_type <> 'A' OR status = 'DRAFT' OR (cost IS NOT NULL AND suggested_price IS NOT NULL)
    )
);
COMMENT ON TABLE  product IS '品項主檔。A/B 雙軌共用一張表，以 track_type 區分';
COMMENT ON COLUMN product.margin_rate IS '冗餘欄位（售價－成本）／售價，寫入時計算。毛利率是排行高頻篩選條件，即時算會讓 §7.3 的排行索引失效';
COMMENT ON COLUMN product.track_type IS 'A=已有供應商跑完整評分；B=尋源探索中，成案後由 B 改 A（FR-16-2）';
COMMENT ON COLUMN product.target_audience IS '逗號分隔的客群代碼';
COMMENT ON COLUMN product.logistics_condition IS '冷鏈／易碎／常溫…，logistics_risk 扣分的判定輸入（§5.2.2）';
COMMENT ON COLUMN product.shelf_life_days IS '效期天數，inventory_risk 扣分的判定輸入';

-- §7.2 指定索引
CREATE INDEX idx_product_category_status ON product (category_id, status);
CREATE INDEX idx_product_name            ON product (name);
-- B 軌清單以 track_type + sourcing_status 篩選（FR-16-2），另建一支
CREATE INDEX idx_product_track_sourcing  ON product (track_type, sourcing_status);

CREATE TABLE product_image (
    id         BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT       NOT NULL REFERENCES product (id) ON DELETE CASCADE,
    file_path  VARCHAR(500) NOT NULL,
    sort_order INT          NOT NULL DEFAULT 0
);
CREATE INDEX idx_product_image_product ON product_image (product_id, sort_order);


-- ===================================================================
-- 趨勢與關鍵字（§7.2 trend_keyword / product_keyword / trend_daily）
-- ===================================================================

CREATE TABLE trend_keyword (
    id              BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    keyword         VARCHAR(80) NOT NULL UNIQUE,
    geo             VARCHAR(10) NOT NULL DEFAULT 'TW',
    lifecycle       VARCHAR(16)
                    CHECK (lifecycle IN ('EMERGING', 'GROWING', 'PEAK', 'DECLINING', 'STABLE')),
    last_fetched_at TIMESTAMPTZ,
    enabled         BOOLEAN     NOT NULL DEFAULT TRUE
);
COMMENT ON TABLE trend_keyword IS '追蹤中的關鍵字。B 軌以關鍵字為起點，尚未建立 product 時仍可累積熱度';

CREATE TABLE product_keyword (
    product_id BIGINT NOT NULL REFERENCES product (id)       ON DELETE CASCADE,
    keyword_id BIGINT NOT NULL REFERENCES trend_keyword (id) ON DELETE CASCADE,
    PRIMARY KEY (product_id, keyword_id)
);
COMMENT ON TABLE product_keyword IS '品項與關鍵字多對多。一個品項可綁多個關鍵字，熱度取合成值';

CREATE TABLE trend_daily (
    keyword_id BIGINT NOT NULL REFERENCES trend_keyword (id) ON DELETE CASCADE,
    stat_date  DATE   NOT NULL,
    heat_value INT    NOT NULL CHECK (heat_value BETWEEN 0 AND 100),
    -- §7.3：主鍵即為查詢鍵，90 日區間查詢為索引範圍掃描
    PRIMARY KEY (keyword_id, stat_date)
);
COMMENT ON TABLE trend_daily IS '關鍵字每日熱度（0–100 已正規化）。§5.3.3 的斜率由本表計算';


-- ===================================================================
-- 評論與風險分析（§7.2 product_review / review_analysis）
-- ===================================================================

CREATE TABLE product_review (
    id           BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id   BIGINT        NOT NULL REFERENCES product (id) ON DELETE CASCADE,
    source       VARCHAR(50)   NOT NULL,
    content      TEXT          NOT NULL,
    rating       DECIMAL(2, 1) CHECK (rating IS NULL OR rating BETWEEN 0 AND 5),
    reviewed_at  DATE,
    content_hash VARCHAR(64)     NOT NULL,
    created_at   TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT uk_review UNIQUE (product_id, content_hash)
);
COMMENT ON COLUMN product_review.rating IS '原始星等，來源未提供時留 NULL；不以 0 代替，0 會被誤讀為極差評';
COMMENT ON COLUMN product_review.content_hash IS 'SHA-256(content)。重複匯入靠唯一鍵擋掉，不需先查再寫';
-- §7.3：評論表依 product_id 成長，查詢一律帶 product_id
CREATE INDEX idx_review_product_date ON product_review (product_id, reviewed_at DESC);

CREATE TABLE review_analysis (
    review_id   BIGINT      PRIMARY KEY REFERENCES product_review (id) ON DELETE CASCADE,
    sentiment   VARCHAR(16) NOT NULL
                CHECK (sentiment IN ('POSITIVE', 'NEUTRAL', 'NEGATIVE')),
    aspects     VARCHAR(200),
    key_phrase  VARCHAR(50),
    model       VARCHAR(80),
    analyzed_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE  review_analysis IS 'v2.0：評論不再作為加分因子，僅在負面且集中於特定風險主題時扣分（§5.2.2）。與 product_review 共用主鍵（1:1）';
COMMENT ON COLUMN review_analysis.aspects IS 'v2.0 改為風險主題分類（品質／食安／物流破損…），逗號分隔';
CREATE INDEX idx_review_analysis_sentiment ON review_analysis (sentiment);


-- ===================================================================
-- 權重版本與情境權重組（§7.2 weight_version / weight_profile、FR-08）
-- ===================================================================

CREATE TABLE weight_version (
    id                    BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version_no            VARCHAR(16) NOT NULL UNIQUE,
    name                  VARCHAR(80) NOT NULL,
    status                VARCHAR(16) NOT NULL DEFAULT 'DRAFT'
                          CHECK (status IN ('DRAFT', 'ACTIVE', 'RETIRED')),
    effective_from        DATE,
    -- §5.6：v2.0 起各排行榜可獨立設定門檻，故門檻跟著版本走而非寫死在程式
    grade_a_threshold     INT         NOT NULL DEFAULT 85,
    grade_b_threshold     INT         NOT NULL DEFAULT 70,
    category_override_json JSONB,
    change_note           VARCHAR(512),
    approved_by           BIGINT      REFERENCES app_user (id),
    approved_at           TIMESTAMPTZ,
    created_by            BIGINT      REFERENCES app_user (id),
    created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT ck_weight_version_threshold CHECK (grade_a_threshold > grade_b_threshold),
    -- AC-08-3：只有核准過的版本才能生效
    CONSTRAINT ck_weight_version_active CHECK (
        status <> 'ACTIVE' OR (approved_by IS NOT NULL AND effective_from IS NOT NULL)
    )
);
COMMENT ON TABLE  weight_version IS
    '權重版本。v1.0 的 weights_json 已由 weight_profile 逐列取代（v2.0 一版四組情境權重），故不再保留該欄位';
COMMENT ON COLUMN weight_version.category_override_json IS '類別專屬權重覆寫，NULL 表沿用該情境的預設權重';

-- AC-08-2 的資料層保障：全表最多一筆 ACTIVE。
-- 用 partial unique index 而非 CHECK，因為 CHECK 看不到其他列
CREATE UNIQUE INDEX uk_weight_version_active
    ON weight_version (status) WHERE status = 'ACTIVE';

CREATE TABLE weight_profile (
    id         BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version_id BIGINT        NOT NULL REFERENCES weight_version (id) ON DELETE CASCADE,
    scene_type VARCHAR(24)   NOT NULL
               CHECK (scene_type IN ('VIRAL_TOPIC', 'FESTIVAL', 'STAPLE_RESTOCK', 'SEASONAL')),
    factor_code VARCHAR(32)  NOT NULL
               CHECK (factor_code IN ('HEAT_SLOPE', 'HEAT_VOLUME', 'MARGIN', 'CONVERSION',
                                      'PRICE_FIT', 'FESTIVAL', 'CLIMATE')),
    weight     DECIMAL(4, 3) NOT NULL CHECK (weight >= 0 AND weight <= 1),
    CONSTRAINT uk_weight_profile UNIQUE (version_id, scene_type, factor_code)
);
COMMENT ON TABLE weight_profile IS
    '情境權重組。AC-08-1 要求同一 version + scene 的權重加總為 1；跨列的加總無法用 CHECK 表達，由應用層與 §7 的 seed 驗證確保';
COMMENT ON COLUMN weight_profile.factor_code IS '僅允許加分因子。扣分因子固定生效、不參與權重（§5.2.2），故不得出現於此表';


-- ===================================================================
-- 評分（§7.2 product_score / score_factor）
-- ===================================================================

CREATE TABLE product_score (
    id                BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id        BIGINT        NOT NULL REFERENCES product (id) ON DELETE CASCADE,
    weight_version_id BIGINT        NOT NULL REFERENCES weight_version (id),
    period            VARCHAR(8)      NOT NULL,
    scene_type        VARCHAR(24)   NOT NULL
                      CHECK (scene_type IN ('VIRAL_TOPIC', 'FESTIVAL', 'STAPLE_RESTOCK', 'SEASONAL')),
    base_score        DECIMAL(5, 2) NOT NULL,
    bonus_subtotal    DECIMAL(5, 2) NOT NULL,
    risk_penalty      DECIMAL(5, 2) NOT NULL DEFAULT 0,
    penalty_subtotal  DECIMAL(5, 2) NOT NULL DEFAULT 0,
    final_score       DECIMAL(5, 2) NOT NULL,
    grade             VARCHAR(8)      NOT NULL CHECK (grade IN ('A', 'B', 'C')),
    confidence        INT           NOT NULL DEFAULT 100 CHECK (confidence BETWEEN 0 AND 100),
    calculated_at     TIMESTAMPTZ   NOT NULL DEFAULT now(),

    -- §5.5 加權公式：選品分數 = max(0, 加分小計 － 扣分小計)
    CONSTRAINT ck_score_formula CHECK (
        final_score = GREATEST(0, bonus_subtotal - penalty_subtotal)
    ),
    -- §5.5：扣分小計上限 40
    CONSTRAINT ck_score_penalty_cap CHECK (penalty_subtotal BETWEEN 0 AND 40),
    -- §5.6 硬規則：扣分達 20 以上者分級最高只給 B
    CONSTRAINT ck_score_grade_suppress CHECK (
        penalty_subtotal < 20 OR grade <> 'A'
    )
);
COMMENT ON TABLE  product_score IS
    '每次評分產生一筆新紀錄，保留歷史、不覆寫（§5.10）。B 軌品項不評分，故此表僅有 A 軌資料';
COMMENT ON COLUMN product_score.period IS 'ISO 週，如 2026W30';
COMMENT ON COLUMN product_score.base_score IS 'v1.0 欄位名，語意同 bonus_subtotal（加權後未扣分）；為相容既有 API 保留';
COMMENT ON COLUMN product_score.risk_penalty IS 'v1.0 欄位名，語意同 penalty_subtotal；為相容既有 API 保留';
COMMENT ON COLUMN product_score.confidence IS '0–100，扣分規則見 §5.9。低於 50 時 UI 顯示警示標記';

-- §7.2 指定索引：排行查詢
CREATE INDEX idx_score_period_grade ON product_score (period, grade, final_score DESC);
-- 品項詳情要取「最新一筆」評分
CREATE INDEX idx_score_product_calc ON product_score (product_id, calculated_at DESC);

CREATE TABLE score_factor (
    id               BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    score_id         BIGINT         NOT NULL REFERENCES product_score (id) ON DELETE CASCADE,
    factor_code      VARCHAR(32)    NOT NULL
                     CHECK (factor_code IN ('HEAT_SLOPE', 'HEAT_VOLUME', 'MARGIN', 'CONVERSION',
                                            'PRICE_FIT', 'FESTIVAL', 'CLIMATE',
                                            'REVIEW_RISK', 'LOGISTICS_RISK', 'INVENTORY_RISK')),
    raw_value        DECIMAL(12, 4),
    normalized_value DECIMAL(5, 2),
    weight           DECIMAL(4, 3),
    penalty_value    DECIMAL(5, 2),
    is_imputed       BOOLEAN        NOT NULL DEFAULT FALSE,
    is_penalty       BOOLEAN        NOT NULL DEFAULT FALSE,
    data_available   BOOLEAN        NOT NULL DEFAULT TRUE,
    CONSTRAINT uk_score_factor UNIQUE (score_id, factor_code),
    -- 加分因子有權重、沒扣分值；扣分因子相反（§5.2.2 扣分不參與權重）
    CONSTRAINT ck_score_factor_shape CHECK (
        (is_penalty = FALSE AND penalty_value IS NULL)
        OR (is_penalty = TRUE AND weight IS NULL)
    )
);
COMMENT ON TABLE  score_factor IS
    '因子評分透明化的資料基礎，畫面上每根長條直接對應一列（§7.2）';
COMMENT ON COLUMN score_factor.penalty_value IS
    '扣分因子的實際扣分值（正數表示扣掉多少）。規格 §7.2 未明列此欄位，但 §5.5 的扣分小計需逐項還原，故補上';
COMMENT ON COLUMN score_factor.data_available IS
    'FALSE 表該因子無資料：UI 標灰底，權重按比例分攤給其餘因子，且不扣分（§5.7）';
CREATE INDEX idx_score_factor_score ON score_factor (score_id);


-- ===================================================================
-- AI 洞察與風險示警（§7.2 ai_insight / risk_alert）
-- ===================================================================

CREATE TABLE ai_insight (
    id                  BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id          BIGINT        NOT NULL REFERENCES product (id) ON DELETE CASCADE,
    insight_type        VARCHAR(24)   NOT NULL
                        CHECK (insight_type IN ('SELLING_POINT', 'RISK', 'RECOMMENDATION', 'TREND')),
    content_json        JSONB         NOT NULL,
    model               VARCHAR(80),
    prompt_version      VARCHAR(20),
    source_review_count INT           NOT NULL DEFAULT 0,
    prompt_tokens       INT,
    completion_tokens   INT,
    cost_usd            DECIMAL(8, 5) NOT NULL DEFAULT 0,
    generated_at        TIMESTAMPTZ   NOT NULL DEFAULT now(),
    is_current          BOOLEAN       NOT NULL DEFAULT TRUE
);
COMMENT ON TABLE  ai_insight IS 'AI 分析結果。同 product + type 僅一筆 is_current=TRUE，其餘為歷史版本';
COMMENT ON COLUMN ai_insight.source_review_count IS '本次分析引用的評論筆數，供 §6.6 幻覺防護的可追溯性揭露';
COMMENT ON COLUMN ai_insight.cost_usd IS '規格書 §3.2 模型策略為一律使用免費模型，故正常情況為 0，仍保留欄位以便換模型後計費';

-- 同一品項同一類型只能有一筆現行版本
CREATE UNIQUE INDEX uk_ai_insight_current
    ON ai_insight (product_id, insight_type) WHERE is_current = TRUE;

CREATE TABLE risk_alert (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id    BIGINT       NOT NULL REFERENCES product (id) ON DELETE CASCADE,
    risk_type     VARCHAR(30)  NOT NULL,
    severity      VARCHAR(16)  NOT NULL CHECK (severity IN ('HIGH', 'MEDIUM', 'LOW')),
    trigger_value VARCHAR(100),
    status        VARCHAR(16)  NOT NULL DEFAULT 'OPEN'
                  CHECK (status IN ('OPEN', 'ACKNOWLEDGED', 'IGNORED')),
    ignore_reason VARCHAR(300),
    detected_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    handled_at    TIMESTAMPTZ,
    handled_by    BIGINT       REFERENCES app_user (id),

    -- FR-10：忽略需填理由
    CONSTRAINT ck_risk_ignore_reason CHECK (
        status <> 'IGNORED' OR ignore_reason IS NOT NULL
    )
);
COMMENT ON TABLE  risk_alert IS '風險示警。AC-10-2：已忽略者不做實體刪除，只是預設清單不顯示';
COMMENT ON COLUMN risk_alert.trigger_value IS '觸發當下的數值描述，例如「負評率 18%（門檻 15%）」';
CREATE INDEX idx_risk_alert_status ON risk_alert (status, severity, detected_at DESC);
CREATE INDEX idx_risk_alert_product ON risk_alert (product_id);
