-- ===================================================================
-- V2 決策閉環與營運資料表
-- 對應：規格書 §7.2 decision_record / decision_feedback / sales_record /
--       ai_task / ai_task_item / import_batch / import_error / audit_log
-- ===================================================================
-- 拆成獨立 migration 而非併入 V1 的理由：Flyway 的檔案就是變更史，
-- 一個檔案處理一個主題，日後 blame 才看得出「這張表為什麼長這樣」。
-- ===================================================================


-- ===================================================================
-- 資料匯入（§7.2 import_batch / import_error、FR-09）
-- 註：sales_record 參照 import_batch，故批次表必須先建立
-- ===================================================================

CREATE TABLE import_batch (
    id           BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_type    VARCHAR(32)  NOT NULL
                 CHECK (data_type IN ('SALES_RECORD', 'PRODUCT_REVIEW', 'MEMBER_PROFILE', 'PRODUCT_MASTER')),
    file_name    VARCHAR(255) NOT NULL,
    total_rows   INT          NOT NULL DEFAULT 0,
    success_rows INT          NOT NULL DEFAULT 0,
    fail_rows    INT          NOT NULL DEFAULT 0,
    status       VARCHAR(16)  NOT NULL DEFAULT 'PENDING'
                 CHECK (status IN ('PENDING', 'RUNNING', 'SUCCESS', 'FAILED', 'PARTIAL', 'CANCELLED')),
    created_by   BIGINT       REFERENCES app_user (id),
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT ck_import_rows CHECK (success_rows + fail_rows <= total_rows)
);
COMMENT ON TABLE  import_batch IS '匯入批次。FR-09：部分成功時仍寫入正確列，狀態為 PARTIAL';
COMMENT ON COLUMN import_batch.total_rows IS '單檔上限 50,000 列／10MB，超過改採非同步處理（FR-09）';

CREATE TABLE import_error (
    id            BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id      BIGINT      NOT NULL REFERENCES import_batch (id) ON DELETE CASCADE,
    row_number    INT         NOT NULL,
    column_name   VARCHAR(64),
    error_message VARCHAR(500) NOT NULL,
    raw_row       TEXT
);
COMMENT ON TABLE  import_error IS '逐列錯誤明細。AC-09-2：失敗列可下載修正後重新上傳，故需保留 raw_row 原文';
CREATE INDEX idx_import_error_batch ON import_error (batch_id, row_number);


-- ===================================================================
-- 決策與回饋閉環（§7.2 decision_record / decision_feedback、FR-11）
-- ===================================================================

CREATE TABLE decision_record (
    id                 BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id         BIGINT       NOT NULL REFERENCES product (id) ON DELETE CASCADE,
    -- AC-11-1：決策必須綁定一筆評分快照，無快照不可建立決策，故 NOT NULL
    score_id           BIGINT       NOT NULL REFERENCES product_score (id),
    decision           VARCHAR(16)  NOT NULL CHECK (decision IN ('ADOPT', 'WATCH', 'REJECT')),
    followed_ai        BOOLEAN      NOT NULL DEFAULT TRUE,
    ai_insight_id      BIGINT       REFERENCES ai_insight (id),
    first_order_qty    INT,
    expected_list_date DATE,
    reason             VARCHAR(500),
    decided_by         BIGINT       NOT NULL REFERENCES app_user (id),
    decided_at         TIMESTAMPTZ  NOT NULL DEFAULT now(),

    -- AC-11-2：未採納 AI 建議時，理由為必填
    CONSTRAINT ck_decision_reason CHECK (
        followed_ai = TRUE OR (reason IS NOT NULL AND length(btrim(reason)) > 0)
    ),
    -- 採納才需要首批數量
    CONSTRAINT ck_decision_qty CHECK (
        decision <> 'ADOPT' OR first_order_qty IS NOT NULL
    )
);
COMMENT ON TABLE  decision_record IS
    '採購決策。AC-11-6：綁定的評分快照建立後不因權重改版而變動，故 score_id 指向不可變的歷史評分列';
COMMENT ON COLUMN decision_record.ai_insight_id IS '決策當下參考的 AI 建議；AI 未產生建議時可為 NULL';
CREATE INDEX idx_decision_product ON decision_record (product_id, decided_at DESC);
CREATE INDEX idx_decision_decided ON decision_record (decided_at DESC, decision);

CREATE TABLE decision_feedback (
    -- 與 decision_record 1:1，共用主鍵
    decision_id     BIGINT        PRIMARY KEY REFERENCES decision_record (id) ON DELETE CASCADE,
    actual_qty_sold INT           NOT NULL,
    actual_cvr      DECIMAL(6, 4),
    sellout_days    INT,
    return_rate     DECIMAL(5, 4),
    filled_by       BIGINT        NOT NULL REFERENCES app_user (id),
    filled_at       TIMESTAMPTZ   NOT NULL DEFAULT now()
);
COMMENT ON TABLE decision_feedback IS
    '結案回填。FR-11-2 明訂欄位壓在 5 個以內：欄位一多就沒人填，沒人填 FR-15 的權重校準就沒有標籤資料';


-- ===================================================================
-- 銷售紀錄（§7.2 sales_record）
-- ===================================================================

CREATE TABLE sales_record (
    id               BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_date       DATE          NOT NULL,
    product_id       BIGINT        REFERENCES product (id) ON DELETE SET NULL,
    product_name_raw VARCHAR(150)  NOT NULL,
    category_id      BIGINT        REFERENCES category (id),
    price            DECIMAL(10, 2) NOT NULL,
    qty              INT           NOT NULL CHECK (qty >= 0),
    impression       INT,
    audience_tag     VARCHAR(100),
    import_batch_id  BIGINT        REFERENCES import_batch (id)
);
COMMENT ON TABLE  sales_record IS '歷史銷售紀錄，conversion 因子（§5.2.1 歷史轉換率）的資料來源';
COMMENT ON COLUMN sales_record.product_id IS '比對不到品項時為 NULL，仍保留 product_name_raw 供後續人工對應';
COMMENT ON COLUMN sales_record.impression IS '曝光數，NULL 表來源未提供；轉換率 = qty / impression，缺此值即無法算 CVR';
-- §7.2 指定索引
CREATE INDEX idx_sales_date_cat ON sales_record (order_date, category_id);
CREATE INDEX idx_sales_product  ON sales_record (product_id, order_date);


-- ===================================================================
-- AI 任務（§7.2 ai_task / ai_task_item、FR-07）
-- ===================================================================

CREATE TABLE ai_task (
    id             BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_type      VARCHAR(32)   NOT NULL
                   CHECK (task_type IN ('SCENE_CLASSIFY', 'REVIEW_RISK', 'SELLING_POINT',
                                        'RECOMMENDATION', 'TREND_INTERPRET', 'SOURCING_SCOUT',
                                        'WEIGHT_CALIBRATION')),
    status         VARCHAR(16)   NOT NULL DEFAULT 'PENDING'
                   CHECK (status IN ('PENDING', 'RUNNING', 'SUCCESS', 'FAILED', 'PARTIAL', 'CANCELLED')),
    total_count    INT           NOT NULL DEFAULT 0,
    success_count  INT           NOT NULL DEFAULT 0,
    fail_count     INT           NOT NULL DEFAULT 0,
    total_cost_usd DECIMAL(10, 5) NOT NULL DEFAULT 0,
    created_by     BIGINT        REFERENCES app_user (id),
    started_at     TIMESTAMPTZ,
    finished_at    TIMESTAMPTZ,

    CONSTRAINT ck_ai_task_counts CHECK (success_count + fail_count <= total_count)
);
COMMENT ON TABLE  ai_task IS
    'AI 批次任務。task_type 同時決定預算池（FR-07）：SOURCING_SCOUT 走 B 軌池，耗盡不得影響 A 軌批次（AC-07-2）';

CREATE TABLE ai_task_item (
    id            BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id       BIGINT      NOT NULL REFERENCES ai_task (id) ON DELETE CASCADE,
    product_id    BIGINT      REFERENCES product (id) ON DELETE CASCADE,
    status        VARCHAR(16) NOT NULL DEFAULT 'PENDING'
                  CHECK (status IN ('PENDING', 'RUNNING', 'SUCCESS', 'FAILED', 'CANCELLED')),
    error_message VARCHAR(500),
    raw_response  TEXT,
    duration_ms   INT
);
COMMENT ON TABLE  ai_task_item IS '任務逐項結果。FR-07 支援「重跑失敗項」，故失敗列需保留可重試的狀態';
COMMENT ON COLUMN ai_task_item.raw_response IS
    '模型原始回應。免費模型的 JSON 格式遵循度不穩（§3.2），驗證失敗時要靠原文除錯';
COMMENT ON COLUMN ai_task_item.product_id IS '權重校準等非品項層級的任務為 NULL';
CREATE INDEX idx_ai_task_item_task ON ai_task_item (task_id, status);


-- ===================================================================
-- 稽核紀錄（§7.2 audit_log）
-- ===================================================================

CREATE TABLE audit_log (
    id          BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT      REFERENCES app_user (id),
    action      VARCHAR(64) NOT NULL,
    entity_type VARCHAR(64) NOT NULL,
    entity_id   BIGINT,
    before_json JSONB,
    after_json  JSONB,
    ip          VARCHAR(45),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE  audit_log IS '稽核軌跡。BUYER_LEAD 與 SYS_ADMIN 可檢視（§2.1）';
COMMENT ON COLUMN audit_log.ip IS '長度 45 以容納 IPv6（含 IPv4-mapped 形式）';
COMMENT ON COLUMN audit_log.user_id IS '系統排程觸發的變更為 NULL';
CREATE INDEX idx_audit_entity  ON audit_log (entity_type, entity_id, created_at DESC);
CREATE INDEX idx_audit_created ON audit_log (created_at DESC);
