-- ===================================================================
-- V3 熱度資料層（v2.0 新增，FR-14）
-- 對應：規格書 §7.2 heat_source / heat_reading / manual_heat_tag
-- ===================================================================


CREATE TABLE heat_source (
    id               BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_code      VARCHAR(32)   NOT NULL UNIQUE
                     CHECK (source_code IN ('THREADS', 'GOOGLE_TRENDS', 'INSTAGRAM', 'MANUAL')),
    adapter_type     VARCHAR(32)   NOT NULL CHECK (adapter_type IN ('REST', 'MANUAL')),
    composite_weight DECIMAL(4, 3) NOT NULL DEFAULT 0
                     CHECK (composite_weight >= 0 AND composite_weight <= 1),
    availability     VARCHAR(16)   NOT NULL DEFAULT 'AVAILABLE'
                     CHECK (availability IN ('AVAILABLE', 'DEGRADED', 'UNAVAILABLE')),
    quota_used       INT           NOT NULL DEFAULT 0,
    quota_limit      INT,
    last_fetched_at  TIMESTAMPTZ,
    enabled          BOOLEAN       NOT NULL DEFAULT TRUE
);
COMMENT ON TABLE  heat_source IS
    '熱度來源註冊表。Facebook／TikTok／小紅書不列入：三者均無合法的程式化資料管道（附錄 C），改由 MANUAL 人工標記涵蓋';
COMMENT ON COLUMN heat_source.composite_weight IS
    '§5.3.2 合成權重。來源降級時此權重視為 0，其餘來源按比例重新正規化，不阻斷評分流程';
COMMENT ON COLUMN heat_source.quota_limit IS 'NULL 表無額度上限（如人工標記）';

CREATE TABLE heat_reading (
    id                       BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id                BIGINT         NOT NULL REFERENCES heat_source (id)   ON DELETE CASCADE,
    keyword_id               BIGINT         NOT NULL REFERENCES trend_keyword (id) ON DELETE CASCADE,
    reading_date             DATE           NOT NULL,
    raw_value                DECIMAL(12, 3) NOT NULL,
    percentile_within_source DECIMAL(5, 2)
                             CHECK (percentile_within_source IS NULL
                                    OR percentile_within_source BETWEEN 0 AND 100),
    CONSTRAINT uk_heat_reading UNIQUE (keyword_id, source_id, reading_date)
);
COMMENT ON TABLE  heat_reading IS
    '各來源熱度原始讀值（時序）。§5.3.2：各來源量級不可比，故先在來源內百分位化再依合成權重加總';
COMMENT ON COLUMN heat_reading.raw_value IS '來源原始值，量級因來源而異，不可跨來源直接比較';
COMMENT ON COLUMN heat_reading.percentile_within_source IS '同來源內百分位（0–100），合成時實際採用的是這一欄';
-- §7.2 指定索引（唯一鍵已覆蓋此組合，額外補一支以 reading_date 起頭的區間查詢用索引）
CREATE INDEX idx_heat_reading_date ON heat_reading (reading_date, source_id);

CREATE TABLE manual_heat_tag (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_url  VARCHAR(512) NOT NULL,
    platform    VARCHAR(24)  NOT NULL
                CHECK (platform IN ('FACEBOOK', 'TIKTOK', 'XIAOHONGSHU', 'THREADS', 'INSTAGRAM', 'OTHER')),
    heat_level  SMALLINT     NOT NULL CHECK (heat_level BETWEEN 1 AND 5),
    product_id  BIGINT       REFERENCES product (id)       ON DELETE CASCADE,
    keyword_id  BIGINT       REFERENCES trend_keyword (id) ON DELETE CASCADE,
    observed_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    tagged_by   BIGINT       NOT NULL REFERENCES app_user (id),
    note        VARCHAR(255),

    -- FR-14-1：關聯品項／關鍵字為必填，可綁 A 軌品項或 B 軌關鍵字，至少擇一
    CONSTRAINT ck_manual_tag_target CHECK (
        product_id IS NOT NULL OR keyword_id IS NOT NULL
    )
);
COMMENT ON TABLE  manual_heat_tag IS
    '人工熱度標記（FR-14-1）。刻意只儲存連結與評級、不擷取頁面內容，避開重製與個資問題';
COMMENT ON COLUMN manual_heat_tag.heat_level IS
    '1–5，附文字錨點：1 零星討論 → 5 洗版等級。§5.3.2：標記人數決定信心係數（1 人 0.6、2 人 0.8、3 人以上 1.0）';
COMMENT ON COLUMN manual_heat_tag.observed_at IS
    '觀察時間。時間衰減以此為基準：14 天後 ×0.5、30 天後 ×0（AC-14-2）';
COMMENT ON COLUMN manual_heat_tag.platform IS '由 source_url 自動解析，判定錯誤時可手動覆寫（AC-14-1）';
CREATE INDEX idx_manual_tag_product ON manual_heat_tag (product_id, observed_at DESC);
CREATE INDEX idx_manual_tag_keyword ON manual_heat_tag (keyword_id, observed_at DESC);
