-- ===================================================================
-- V4 情境判定與時間窗（v2.0 新增，FR-17 / §5.4）
-- 對應：規格書 §7.2 scene_classification_log / festival_calendar /
--       category_lead_time / item_festival_affinity / climate_normal
-- ===================================================================


-- ===================================================================
-- 情境判定紀錄（§7.2 scene_classification_log）
-- ===================================================================

CREATE TABLE scene_classification_log (
    id               BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id       BIGINT        NOT NULL REFERENCES product (id) ON DELETE CASCADE,
    ai_scene_type    VARCHAR(24)
                     CHECK (ai_scene_type IN ('VIRAL_TOPIC', 'FESTIVAL', 'STAPLE_RESTOCK', 'SEASONAL')),
    ai_confidence    DECIMAL(3, 2) CHECK (ai_confidence IS NULL OR ai_confidence BETWEEN 0 AND 1),
    ai_reasoning     TEXT,
    final_scene_type VARCHAR(24)   NOT NULL
                     CHECK (final_scene_type IN ('VIRAL_TOPIC', 'FESTIVAL', 'STAPLE_RESTOCK', 'SEASONAL')),
    overridden_by    BIGINT        REFERENCES app_user (id),
    override_reason  VARCHAR(255),
    created_at       TIMESTAMPTZ   NOT NULL DEFAULT now(),

    -- §7.2：覆寫理由於覆寫時必填
    CONSTRAINT ck_scene_override_reason CHECK (
        overridden_by IS NULL OR (override_reason IS NOT NULL AND length(btrim(override_reason)) > 0)
    )
);
COMMENT ON TABLE  scene_classification_log IS
    '情境判定與人工覆寫紀錄，是權重校準的關鍵訊號來源。覆寫率過高代表判定規則需調整（FR-11-3）';
COMMENT ON COLUMN scene_classification_log.ai_scene_type IS
    'AI 判定結果。信心值低於 0.5 或 Schema 驗證失敗時本欄為 NULL，final_scene_type 退回 STAPLE_RESTOCK（§5.4）';
COMMENT ON COLUMN scene_classification_log.ai_reasoning IS
    '§5.4 約束：AI 必須輸出判定理由與依據訊號，否則判定不可稽核';
CREATE INDEX idx_scene_log_product ON scene_classification_log (product_id, created_at DESC);
-- 覆寫率統計會掃「有覆寫者」的列，建 partial index 避免全表掃描
CREATE INDEX idx_scene_log_overridden ON scene_classification_log (created_at DESC)
    WHERE overridden_by IS NOT NULL;


-- ===================================================================
-- 節慶檔期（§7.2 festival_calendar / category_lead_time / item_festival_affinity）
-- ===================================================================

CREATE TABLE festival_calendar (
    id            BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    festival_code VARCHAR(32) NOT NULL,
    festival_name VARCHAR(50) NOT NULL,
    calendar_type VARCHAR(8)  NOT NULL CHECK (calendar_type IN ('LUNAR', 'SOLAR')),
    festival_date DATE        NOT NULL,
    year          INT         NOT NULL,
    CONSTRAINT uk_festival UNIQUE (festival_code, year),
    -- festival_date 必須落在其標示的年度內，避免農曆換算錯年
    CONSTRAINT ck_festival_year CHECK (EXTRACT(YEAR FROM festival_date) = year)
);
COMMENT ON TABLE  festival_calendar IS
    '節慶檔期。AC-17-1：LUNAR 類的國曆日期須由農曆換算自動產生，不可逐年人工輸入';
COMMENT ON COLUMN festival_calendar.festival_date IS '換算後的國曆日期。LUNAR 節慶每年不同，故以 (code, year) 為唯一鍵';

CREATE TABLE category_lead_time (
    category_id    BIGINT PRIMARY KEY REFERENCES category (id) ON DELETE CASCADE,
    lead_time_days INT    NOT NULL CHECK (lead_time_days >= 0)
);
COMMENT ON TABLE category_lead_time IS
    '品類前置天數。AC-17-3：同一份資料同時供 FR-17 節慶時間窗與 FR-16 時效落差使用，只維護一份';

CREATE TABLE item_festival_affinity (
    product_id    BIGINT        NOT NULL REFERENCES product (id) ON DELETE CASCADE,
    festival_code VARCHAR(32)   NOT NULL,
    affinity      DECIMAL(3, 2) NOT NULL CHECK (affinity BETWEEN 0 AND 1),
    PRIMARY KEY (product_id, festival_code)
);
COMMENT ON TABLE  item_festival_affinity IS
    '品項與節慶的關聯度。初期人工建立，累積後由 AI 建議、人審核（FR-17-1）';
COMMENT ON COLUMN item_festival_affinity.festival_code IS
    '不外鍵到 festival_calendar：關聯度是「跨年度」的品項屬性，而 festival_calendar 逐年一列';
COMMENT ON COLUMN item_festival_affinity.affinity IS
    '0–1。節慶因子 = 關聯度 × 時間窗權重(日期, 節慶日, 品類前置天數)（FR-17-1）';


-- ===================================================================
-- 季節氣候基準（§7.2 climate_normal）
-- ===================================================================

CREATE TABLE climate_normal (
    region_code      VARCHAR(16)   NOT NULL,
    month            SMALLINT      NOT NULL CHECK (month BETWEEN 1 AND 12),
    avg_temp         DECIMAL(4, 1) NOT NULL,
    rain_probability DECIMAL(4, 1) NOT NULL CHECK (rain_probability BETWEEN 0 AND 100),
    PRIMARY KEY (region_code, month)
);
COMMENT ON TABLE climate_normal IS
    '歷史同期氣候統計，僅供選品評分使用。FR-17-2 明訂短期天氣預報不得計入分數（AC-17-4）：'
    '預報僅 7–14 天可信，而備貨週期常超過三週，時序對不上';
COMMENT ON COLUMN climate_normal.rain_probability IS '降雨機率百分比（0–100）';
