-- ===================================================================
-- V5 開團快照、尋源探索與權重校準（v2.0 新增）
-- 對應：規格書 §7.2 campaign_snapshot / campaign_result /
--       sourcing_candidate / calibration_report
-- ===================================================================


-- ===================================================================
-- 開團快照與結果（§7.2 campaign_snapshot / campaign_result、FR-11）
-- ===================================================================

CREATE TABLE campaign_snapshot (
    id                BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    decision_id       BIGINT        NOT NULL UNIQUE REFERENCES decision_record (id) ON DELETE CASCADE,
    score             DECIMAL(5, 2) NOT NULL,
    grade             VARCHAR(8)      NOT NULL CHECK (grade IN ('A', 'B', 'C')),
    bonus_subtotal    DECIMAL(5, 2) NOT NULL,
    penalty_subtotal  DECIMAL(5, 2) NOT NULL,
    weight_version_id BIGINT        NOT NULL REFERENCES weight_version (id),
    scene_type        VARCHAR(24)   NOT NULL
                      CHECK (scene_type IN ('VIRAL_TOPIC', 'FESTIVAL', 'STAPLE_RESTOCK', 'SEASONAL')),
    scene_overridden  BOOLEAN       NOT NULL DEFAULT FALSE,
    factor_values     JSONB         NOT NULL,
    source_availability JSONB,
    created_at        TIMESTAMPTZ   NOT NULL DEFAULT now()
);
COMMENT ON TABLE  campaign_snapshot IS
    '開團當下的完整評分快照。AC-11-6：建立後不因權重改版而變動，故因子值以 JSON 就地凍結，'
    '不靠 join 回 score_factor（那些列會隨重新評分而新增，語意會漂移）';
COMMENT ON COLUMN campaign_snapshot.factor_values IS '各因子原始值與正規化值，例如 {"HEAT_SLOPE":{"raw":3.4,"norm":88,"weight":0.55}}';
COMMENT ON COLUMN campaign_snapshot.source_availability IS '當時各熱度來源狀態，用於事後解釋「這筆分數少了哪些來源」';
COMMENT ON COLUMN campaign_snapshot.scene_overridden IS 'TRUE 表情境被人工覆寫；FR-11-3 的覆寫率指標由此統計';

CREATE TABLE campaign_result (
    id              BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    decision_id     BIGINT        NOT NULL UNIQUE REFERENCES decision_record (id) ON DELETE CASCADE,
    actual_qty      INT           NOT NULL CHECK (actual_qty >= 0),
    sellout_status  VARCHAR(24)   NOT NULL
                    CHECK (sellout_status IN ('EARLY_SELLOUT', 'ON_TIME', 'BELOW_TARGET', 'SLOW')),
    return_rate     DECIMAL(5, 2) CHECK (return_rate IS NULL OR return_rate BETWEEN 0 AND 100),
    realized_margin DECIMAL(5, 2),
    post_note_code  VARCHAR(32)
                    CHECK (post_note_code IN ('FASTER_THAN_EXPECTED', 'HEAT_FADED',
                                              'QUALITY_ISSUE', 'LOGISTICS_ISSUE')),
    post_note_text  VARCHAR(255),
    filled_by       BIGINT        NOT NULL REFERENCES app_user (id),
    filled_at       TIMESTAMPTZ   NOT NULL DEFAULT now()
);
COMMENT ON TABLE  campaign_result IS
    '開團結果，FR-15 權重校準的標籤資料。沒有這張表，統計迴歸完全不成立';
COMMENT ON COLUMN campaign_result.realized_margin IS '實現毛利率（百分比），對照當初預估毛利';
COMMENT ON COLUMN campaign_result.post_note_code IS '單選代碼；自由文字放 post_note_text，避免結案表單變長而沒人填';


-- ===================================================================
-- B 軌尋源候選（§7.2 sourcing_candidate、FR-16）
-- ===================================================================

CREATE TABLE sourcing_candidate (
    id                      BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    keyword_id              BIGINT      NOT NULL REFERENCES trend_keyword (id) ON DELETE CASCADE,
    category_id             BIGINT      REFERENCES category (id),
    heat_stage              VARCHAR(16) NOT NULL
                            CHECK (heat_stage IN ('RISING', 'PLATEAU', 'DECLINING')),
    stage_weeks             SMALLINT    CHECK (stage_weeks IS NULL OR stage_weeks >= 0),
    estimated_lifespan_days INT         NOT NULL CHECK (estimated_lifespan_days >= 0),
    lead_time_days          INT         NOT NULL CHECK (lead_time_days >= 0),
    time_gap_days           INT         NOT NULL,
    status                  VARCHAR(24) NOT NULL DEFAULT 'PENDING'
                            CHECK (status IN ('PENDING', 'SOURCING', 'URGENT', 'PROMOTED', 'REJECTED')),
    scout_report            TEXT,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT now(),

    -- §5.8：時效落差 = 預估熱度剩餘壽命 － 預估尋源前置期
    CONSTRAINT ck_sourcing_gap CHECK (
        time_gap_days = estimated_lifespan_days - lead_time_days
    ),
    -- AC-16-4：落差小於 0 者自動標記淘汰，不可加入尋源清單
    CONSTRAINT ck_sourcing_reject CHECK (
        time_gap_days >= 0 OR status = 'REJECTED'
    )
);
COMMENT ON TABLE  sourcing_candidate IS
    'B 軌尋源優先序。AC-16-2：B 軌不產生選品分數，排序依據是時效落差而非熱度 —— '
    '熱度最高但來不及的品項排在前面不具意義';
COMMENT ON COLUMN sourcing_candidate.estimated_lifespan_days IS
    '預估熱度剩餘壽命。§5.8 初始經驗值：上升期 56、高原期 1–2 週 42、高原期 3 週以上 35、衰退期 17';
COMMENT ON COLUMN sourcing_candidate.lead_time_days IS
    '預估尋源前置期，預設取 category_lead_time，採購可覆寫（FR-16-2）';
COMMENT ON COLUMN sourcing_candidate.time_gap_days IS
    '時效落差。這是否決條件而非加權因子：寫成扣分的話高熱度會把它蓋過去，但「來不及」是不可交易的事實（FR-16-1）';
-- FR-16-2：以時效落差為主排序依據
CREATE INDEX idx_sourcing_gap    ON sourcing_candidate (status, time_gap_days);
CREATE INDEX idx_sourcing_keyword ON sourcing_candidate (keyword_id);


-- ===================================================================
-- 權重校準報告（§7.2 calibration_report、FR-15）
-- ===================================================================

CREATE TABLE calibration_report (
    id                 BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quarter            VARCHAR(8)  NOT NULL UNIQUE,
    sample_size        INT         NOT NULL CHECK (sample_size >= 0),
    regression_result  JSONB       NOT NULL,
    ai_interpretation  TEXT,
    backtest_result    JSONB,
    status             VARCHAR(16) NOT NULL DEFAULT 'PENDING'
                       CHECK (status IN ('PENDING', 'APPROVED', 'PARTIAL', 'REJECTED')),
    reviewed_by        BIGINT      REFERENCES app_user (id),
    reviewed_at        TIMESTAMPTZ,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),

    -- AC-15-3：校準建議須經 BUYER_LEAD 核准才產生新權重版本
    CONSTRAINT ck_calibration_review CHECK (
        status = 'PENDING' OR reviewed_by IS NOT NULL
    )
);
COMMENT ON TABLE  calibration_report IS
    '季度權重校準報告（FR-15）。分工原則：統計決定數字、AI 負責解釋、人負責核准';
COMMENT ON COLUMN calibration_report.quarter IS '如 2026Q3';
COMMENT ON COLUMN calibration_report.sample_size IS
    'AC-15-1：樣本數低於 200 時畫面必須顯示效度警示，且警示不可關閉';
COMMENT ON COLUMN calibration_report.regression_result IS
    'AC-15-2：建議權重必須由統計迴歸產生，AI 僅解讀不產生數值，故數字只從這一欄來';
COMMENT ON COLUMN calibration_report.backtest_result IS
    '平權／現行版本／建議版本三者的相關係數與 A 級達標率比較（AC-15-4）';
