-- ===================================================================
-- DRAFT - Agent 5: TrendInterpreterAgent output persistence
--
-- This file intentionally lives outside db/migration. Flyway must not run it
-- until the matching entity/repository/service is implemented and reviewed.
-- Move it into db/migration only when Agent 5 is ready to be deployed.
-- ===================================================================

CREATE TABLE trend_interpretation (
    id                      BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    keyword_id              BIGINT       NOT NULL REFERENCES trend_keyword (id) ON DELETE CASCADE,
    heat_stage              VARCHAR(16)  NOT NULL
                            CHECK (heat_stage IN ('RISING', 'PLATEAU', 'DECLINING')),
    stage_weeks             SMALLINT     NOT NULL CHECK (stage_weeks >= 0),
    estimated_lifespan_days INT          NOT NULL CHECK (estimated_lifespan_days >= 0),
    input_snapshot          JSONB        NOT NULL,
    fallback_applied        BOOLEAN      NOT NULL DEFAULT FALSE,
    fallback_reason         VARCHAR(64),
    model                   VARCHAR(80),
    prompt_version          VARCHAR(20),
    generated_at            TIMESTAMPTZ  NOT NULL DEFAULT now(),
    is_current              BOOLEAN      NOT NULL DEFAULT TRUE,

    CONSTRAINT ck_trend_interpretation_fallback CHECK (
        (fallback_applied AND fallback_reason IS NOT NULL
            AND length(btrim(fallback_reason)) > 0)
        OR (NOT fallback_applied AND fallback_reason IS NULL)
    )
);

COMMENT ON TABLE trend_interpretation IS
    'Agent 5 趨勢階段與剩餘壽命判定歷史。以 keyword 為主體，供 A 軌趨勢畫面與 B 軌時效落差共用';
COMMENT ON COLUMN trend_interpretation.input_snapshot IS
    '本次判定使用的近 90 日窗口摘要、7/30 日斜率及各來源狀態；保存輸入快照以便重現判定';
COMMENT ON COLUMN trend_interpretation.fallback_applied IS
    'TRUE 表 LLM 失敗後使用規格 §6.3 的規則式判定';

CREATE UNIQUE INDEX uk_trend_interpretation_current
    ON trend_interpretation (keyword_id) WHERE is_current = TRUE;
CREATE INDEX idx_trend_interpretation_history
    ON trend_interpretation (keyword_id, generated_at DESC);

