export * from './authController.service';
import { AuthControllerService } from './authController.service';
export * from './authController.serviceInterface';
export * from './categoryController.service';
import { CategoryControllerService } from './categoryController.service';
export * from './categoryController.serviceInterface';
export * from './productController.service';
import { ProductControllerService } from './productController.service';
export * from './productController.serviceInterface';
export * from './riskAlertController.service';
import { RiskAlertControllerService } from './riskAlertController.service';
export * from './riskAlertController.serviceInterface';
export * from './supplierController.service';
import { SupplierControllerService } from './supplierController.service';
export * from './supplierController.serviceInterface';
export * from './trendController.service';
import { TrendControllerService } from './trendController.service';
export * from './trendController.serviceInterface';
export * from './weightVersionController.service';
import { WeightVersionControllerService } from './weightVersionController.service';
export * from './weightVersionController.serviceInterface';
export const APIS = [AuthControllerService, CategoryControllerService, ProductControllerService, RiskAlertControllerService, SupplierControllerService, TrendControllerService, WeightVersionControllerService];
