/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApiResponseAuthenticatedUser } from '../model/models';
import { ApiResponseLoginResult } from '../model/models';
import { ApiResponseTokenPair } from '../model/models';
import { ApiResponseVoid } from '../model/models';
import { LoginRequest } from '../model/models';
import { RefreshRequest } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface LoginRequestParams {
    loginRequest: LoginRequest;
}

export interface LogoutRequestParams {
    refreshRequest: RefreshRequest;
}

export interface RefreshRequestParams {
    refreshRequest: RefreshRequest;
}


export interface AuthControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
* @param requestParameters
     */
    login(requestParameters: LoginRequestParams, extraHttpRequestParams?: any): Observable<ApiResponseLoginResult>;

    /**
     * 
     * 
* @param requestParameters
     */
    logout(requestParameters: LogoutRequestParams, extraHttpRequestParams?: any): Observable<ApiResponseVoid>;

    /**
     * 
     * 
*/
    me(extraHttpRequestParams?: any): Observable<ApiResponseAuthenticatedUser>;

    /**
     * 
     * 
* @param requestParameters
     */
    refresh(requestParameters: RefreshRequestParams, extraHttpRequestParams?: any): Observable<ApiResponseTokenPair>;

}
