/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApiResponsePageResponseProductListItem } from '../model/models';
import { ApiResponseProductDetail } from '../model/models';
import { ApiResponseProductSaveResult } from '../model/models';
import { ApiResponseVoid } from '../model/models';
import { Pageable } from '../model/models';
import { ProductRequest } from '../model/models';
import { ProductStatusChangeRequest } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface DeleteRequestParams {
    id: number;
}

export interface ChangeStatusRequestParams {
    id: number;
    productStatusChangeRequest: ProductStatusChangeRequest;
}

export interface CreateProductRequestParams {
    productRequest: ProductRequest;
}

export interface GetRequestParams {
    id: number;
}

export interface ListProductsRequestParams {
    pageable: Pageable;
    keyword?: string;
    categoryId?: number;
    supplierId?: number;
    trackType?: 'A' | 'B';
    sourcingStatus?: 'PENDING' | 'SOURCING' | 'URGENT' | 'PROMOTED' | 'REJECTED';
    status?: 'DRAFT' | 'EVALUATING' | 'WATCHING' | 'ADOPTED' | 'LISTED' | 'REJECTED';
}

export interface UpdateProductRequestParams {
    id: number;
    productRequest: ProductRequest;
}


export interface ProductControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
* @param requestParameters
     */
    _delete(requestParameters: DeleteRequestParams, extraHttpRequestParams?: any): Observable<ApiResponseVoid>;

    /**
     * 
     * 
* @param requestParameters
     */
    changeStatus(requestParameters: ChangeStatusRequestParams, extraHttpRequestParams?: any): Observable<ApiResponseProductDetail>;

    /**
     * 
     * 
* @param requestParameters
     */
    createProduct(requestParameters: CreateProductRequestParams, extraHttpRequestParams?: any): Observable<ApiResponseProductSaveResult>;

    /**
     * 
     * 
* @param requestParameters
     */
    get(requestParameters: GetRequestParams, extraHttpRequestParams?: any): Observable<ApiResponseProductDetail>;

    /**
     * 
     * 
* @param requestParameters
     */
    listProducts(requestParameters: ListProductsRequestParams, extraHttpRequestParams?: any): Observable<ApiResponsePageResponseProductListItem>;

    /**
     * 
     * 
* @param requestParameters
     */
    updateProduct(requestParameters: UpdateProductRequestParams, extraHttpRequestParams?: any): Observable<ApiResponseProductSaveResult>;

}
