/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApiResponsePageResponseRiskAlertListItem } from '../model/models';
import { ApiResponseRiskAlertListItem } from '../model/models';
import { Pageable } from '../model/models';
import { RiskIgnoreRequest } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface AcknowledgeRequestParams {
    id: number;
}

export interface IgnoreRequestParams {
    id: number;
    riskIgnoreRequest: RiskIgnoreRequest;
}

export interface ListRisksRequestParams {
    pageable: Pageable;
    status?: 'OPEN' | 'ACKNOWLEDGED' | 'IGNORED';
    severity?: 'HIGH' | 'MEDIUM' | 'LOW';
    type?: string;
    categoryId?: number;
}


export interface RiskAlertControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
* @param requestParameters
     */
    acknowledge(requestParameters: AcknowledgeRequestParams, extraHttpRequestParams?: any): Observable<ApiResponseRiskAlertListItem>;

    /**
     * 
     * 
* @param requestParameters
     */
    ignore(requestParameters: IgnoreRequestParams, extraHttpRequestParams?: any): Observable<ApiResponseRiskAlertListItem>;

    /**
     * 
     * 
* @param requestParameters
     */
    listRisks(requestParameters: ListRisksRequestParams, extraHttpRequestParams?: any): Observable<ApiResponsePageResponseRiskAlertListItem>;

}
