/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { TrendChartProjection } from '../model/models';
import { TrendDetailResponse } from '../model/models';
import { TrendSignalProjection } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface GetTrendChartRequestParams {
    keywordId: number;
}

export interface GetTrendDetailRequestParams {
    keywordId: number;
}


export interface TrendControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
* @param requestParameters
     */
    getTrendChart(requestParameters: GetTrendChartRequestParams, extraHttpRequestParams?: any): Observable<Array<TrendChartProjection>>;

    /**
     * 
     * 
* @param requestParameters
     */
    getTrendDetail(requestParameters: GetTrendDetailRequestParams, extraHttpRequestParams?: any): Observable<TrendDetailResponse>;

    /**
     * 
     * 
*/
    getTrends(extraHttpRequestParams?: any): Observable<Array<TrendSignalProjection>>;

}
