/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApiResponseListWeightVersionSummary } from '../model/models';
import { ApiResponseWeightVersionDetail } from '../model/models';
import { WeightVersionUpsertRequest } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface CreateWeightVersionRequestParams {
    weightVersionUpsertRequest: WeightVersionUpsertRequest;
}

export interface ProfilesRequestParams {
    id: number;
}

export interface UpdateWeightVersionRequestParams {
    id: number;
    weightVersionUpsertRequest: WeightVersionUpsertRequest;
}


export interface WeightVersionControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
*/
    active(extraHttpRequestParams?: any): Observable<ApiResponseWeightVersionDetail>;

    /**
     * 
     * 
* @param requestParameters
     */
    createWeightVersion(requestParameters: CreateWeightVersionRequestParams, extraHttpRequestParams?: any): Observable<ApiResponseWeightVersionDetail>;

    /**
     * 
     * 
*/
    listWeightVersions(extraHttpRequestParams?: any): Observable<ApiResponseListWeightVersionSummary>;

    /**
     * 
     * 
* @param requestParameters
     */
    profiles(requestParameters: ProfilesRequestParams, extraHttpRequestParams?: any): Observable<ApiResponseWeightVersionDetail>;

    /**
     * 
     * 
* @param requestParameters
     */
    updateWeightVersion(requestParameters: UpdateWeightVersionRequestParams, extraHttpRequestParams?: any): Observable<ApiResponseWeightVersionDetail>;

}
